name: Vercel Deploy
description: Deploy project on Vercel
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
        vercel-org-id: ${{ secrets.ORG_ID}} #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
